---@class JobType
---@field id number
---@field contractClass Contract
---@field name string
---@field title string
---@field requireFieldParam bool
---@field requireFruitParam bool

---@class NPC
---@field imageFilename string
---@field title string
---@field index number
---@field finishedMissions number
---@field name string
